version: '2'
services:
    jblog-app:
        image: jblog
        environment:
        # - _JAVA_OPTIONS=-Xmx512m -Xms256m
        - SPRING_PROFILES_ACTIVE=prod,swagger
        - SPRING_DATASOURCE_URL=jdbc:mysql://jblog-mysql:3306/jblog?useUnicode=true&characterEncoding=utf8&useSSL=false
        - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=jblog-elasticsearch:9300
        ports:
        - 8080:8080
    jblog-mysql:
        extends:
            file: mysql.yml
            service: jblog-mysql
    jblog-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jblog-elasticsearch
